### ISSUE TITLE
Are you still selling custom PCBs?

### ISSUE THREAD

**Issue by hkyeollim** [mon/evoluent_better_pcb#1]
Hello, I am using VM4 in South Korea. My wife and I are 3D designers, and we need a vertical mouse with a middle button, and the VM4 is the only mouse that fits our needs. We find the VM4 very useful, but we are experiencing inconvenience due to the poor sensor. I am very glad to have found you through Google. I am using the VM4 in large size, and my wife is using the small size. Are you still selling custom PCBs? We desperately need them. Please reply. Thank you.

mondayoff73@gmail.com

**Comment by mon** [comment]
Just to copy what I sent to your email -

> Yes, I am still selling the PCBs, and they fit the VM4 Large. However, I recently found that the Small size won't fit (there is an internal plastic piece that hits a connector). 
I have made a redesigned pcb that fits the small size, but it doesn't have firmware yet (it uses a new microprocessor). I'm not sure when it will be done as I'm busy in other areas.
